### ISSUE TITLE
window=0 warning

### ISSUE THREAD

**Issue by sambrightman** [BoevaLab/FREEC#13]
I don't understand this warning:

```
     if (WESanalysis==false && window!=0) {
         cerr << "Warning: we recommend setting \"window=0\" for exome sequencing data\n";
     }
```

I understand from the documentation that `window=0` is supposed to be used for WES and read counts are then performed per exon. Is the first part of conditional the wrong way around (should be `WESanalysis==true`)? Inverting this would make the warning redundant though, as it's not currently possible for the `WESanalysis` to be `true` with `window!=0`:

```
     bool WESanalysis = false;
     if (ifTargeted && window == 0)   {
         WESanalysis = true;
     }
```

I notice this because I'm getting the warning all the time without using targets (WGS with window 1000).

**Comment by valeu** [comment]
Actually, you can run FREEC on the WES data with a window=500 and step=250, for example. In this case WESanalysis will be equal to false and ifTargeted == true. Sorry for using such misleading names.
And you are right that WESanalysis==true if and only if window==0. So this warning does not make sense. I have changed it in v10.4 to:

 if (ifTargeted==true && window != 0)   {
         cerr << "Warning: we recommend setting \"window=0\" for exome sequencing data\n";
  }

Thank you a lot for your feedback!

**Comment by sambrightman** [comment]
Great, thanks.
