### ISSUE TITLE
Make graph error

### ISSUE THREAD

**Issue by Gon1976** [BoevaLab/FREEC#132]
Hi,
I use FREEC to plot ploidy in my genome assembly (freec -conf config.txt)
After run freec and obain ratio.txt file I try to make the graph using: cat makeGraph2.0.R | R --slave --args JJ.bam_ratio.txt

After the png files were created, I observe the same "chromosome" repeated 13 times, but my ratio.txt file have information for 481 contigs (chromosomes) but I only can view  graphs for one contig repeated (attached) 
![JJ bam_ratio txt log2](https://github.com/BoevaLab/FREEC/assets/36075600/9c083e99-3833-405f-ac75-907e74667a87)

Can you see the problem? thanks

**Comment by valeu** [comment]
Hi, if you have unconventional chromosome names (i.e., not chr 1 ,2 ,3.. etc), you need to manually modify the script... My apologies.
