### ISSUE TITLE
No normalization although it is requested

### ISSUE THREAD

**Issue by s-juross** [BoevaLab/FREEC#144]
I'm running ControlFREEC with targed NGS data and no control data and in order to normalize I attempted to run the specified on the website I generated a GC-content profile with gccount. 
But even with this specified in the config file, ControlFREEC doesn't normalize either with the GC-content nor with the mappability profile. 
Does somebody have an idea what the problem is? I've attached the config file.
[CNV_config.txt](https://github.com/user-attachments/files/16173985/CNV_config.txt)
Am I right that CNVs without normalization are basically useless?

**Comment by valeu** [comment]
Hi, I franckly don't think that it makes sense to try to call CNA on targeted sequencing data without controls: the capture bias is very strong. I suggest the OncoCNV tool for amplicon panels - there one can use many unmatched samples as controls.

**Comment by s-juross** [comment]
Thank you for the answer!
