### ISSUE TITLE
Cannot generate BAF files

### ISSUE THREAD

**Issue by ericpeny** [BoevaLab/FREEC#16]
Dear FREEC developer,

I have some issue with generating BAF files. I test several combinations of input files, first I provide bam file for sample, bam file for control and use makepileup option in BAF and provide vcf for SNPfile. 
Second, I provide bam file for sample, pileup file for control and provide vcf for SNPfile.
Third, I provide pileup files for sample as well as control and provide vcf for SNPfile.
They don't give me the BAF files. Did I miss something?

Also, in the manual, it says mateOrientation=0,RF,FR,FF are related to single end, pair end, mate pair, solid mate pair. However, in the WGS example configure file, it says use 0 for sorted sam and bam. I am confused here. I am using sorted Bam files as input, illumina pair end results, what should I put here?

Thank you very much!
Yu

**Comment by valeu** [comment]
Dear Yu,

do you get BAF profiles when you simply provide pileups for both sample and control?

**Comment by pengyuguai** [comment]
Sorry for replying so late.
Some of my samples were able to get BAF now. However, some of them were not. There were some output as follows, are they normal or how can I change the parameters to fix it?

Number of EM iterations :0
..Copy number profile normalization -> done
..Calculating breakpoints, breakPointThreshold = 0.8
..You have zero windows with reads. Will try to continue anyway..
..You have zero windows with reads. Will try to continue anyway..
..You have zero windows with reads. Will try to continue anyway..



Warning: we recommend setting "window=0" for exome sequencing data
Error: zero reads in windows with the GC-content around 0.35 with interval 0.01, will try again with 0.04
Error: zero reads in windows with the GC-content around 0.5 with interval 0.01, will try again with 0.04
Error: zero reads in windows with the GC-content around 0.55 with interval 0.01, will try again with 0.04
Error: zero reads in windows with the GC-content around 0.35 with interval 0.01, will try again with 0.04
Error: zero reads in windows with the GC-content around 0.55 with interval 0.01, will try again with 0.04
Error in linear regression, code: -1
Error in EM => unable to calculate normalized profile
Error: zero reads in windows with the GC-content around 0.35 with interval 0.01, will try again with 0.04
Error: zero reads in windows with the GC-content around 0.5 with interval 0.01, will try again with 0.04
Error: zero reads in windows with the GC-content around 0.55 with interval 0.01, will try again with 0.04
Error: zero reads in windows with the GC-content around 0.35 with interval 0.01, will try again with 0.04
Error: zero reads in windows with the GC-content around 0.55 with interval 0.01, will try again with 0.04
Error in linear regression, code: -1
Error in EM => unable to calculate normalized profile
..failed to run segmentation on chr1
..failed to run segmentation on chr2
..failed to run segmentation on chr3

Thank you very much.
Yu

**Comment by valeu** [comment]
Dear Yu,
The output indicates an error. Please send me to valentina dot boeva at inserm dot fr your config file and your complete output?

**Comment by pengyuguai** [comment]
Thank you for your reply. I sent my config and output to you. Please check.

**Comment by othomps101** [comment]
Any update on this issue? I am getting the same error.
Error: zero reads in windows with the GC-content around

**Comment by valeu** [comment]
Dear Olivia,
Could you share your config file and the complete output of FREEC into the command line, please?

**Comment by lizhan96** [comment]
dear developer
the following is the command i uesd, and i get some error, could you please give me a hand?
The attached is the config file I uesd.
Thanks.

`/disk/soft/FREEC-11.1/src/freec -conf config_hg38.txt
`
```
Error: zero reads in windows with the GC-content around 0.35 with interval 0.01, will try again with 0.04
Error: zero reads in windows with the GC-content around 0.35 with interval 0.04
Unable to proceed..
Try to rerun the program with higher number of reads
```

[config_hg38.txt](https://github.com/BoevaLab/FREEC/files/6714688/config_hg38.txt)

**Comment by Yixiangzhang1996** [comment]
> dear developer the following is the command i uesd, and i get some error, could you please give me a hand? The attached is the config file I uesd. Thanks.
> 
> `/disk/soft/FREEC-11.1/src/freec -conf config_hg38.txt `
> 
> ```
> Error: zero reads in windows with the GC-content around 0.35 with interval 0.01, will try again with 0.04
> Error: zero reads in windows with the GC-content around 0.35 with interval 0.04
> Unable to proceed..
> Try to rerun the program with higher number of reads
> ```
> 
> [config_hg38.txt](https://github.com/BoevaLab/FREEC/files/6714688/config_hg38.txt)

how do u solve this problem？
