### ISSUE TITLE
compilation error in Mac OSX

### ISSUE THREAD

**Issue by krsachin** [BoevaLab/FREEC#17]
I had tried to install FREEC-10.2 on mac osx but its fail with following error. Could you help me on this issue?
 
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.freec init
make[1]: Nothing to be done for `init'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.freec depend
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.freec all
c++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o main.o main.cpp
c++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o ConfigFile.o ConfigFile.cpp
c++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o Chameleon.o Chameleon.cpp
c++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o GenomeDensity.o GenomeDensity.cpp
c++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o Help.o Help.cpp
c++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o myFunc.o myFunc.cpp
myFunc.cpp:54:12: warning: using the result of an assignment as a condition
      without parentheses [-Wparentheses]
  for (; c = *str++; ++jj) {
         ~~^~~~~~~~
myFunc.cpp:54:12: note: place parentheses around the assignment to silence this
      warning
  for (; c = *str++; ++jj) {
           ^
         (         )
myFunc.cpp:54:12: note: use '==' to turn this assignment into an equality
      comparison
  for (; c = *str++; ++jj) {
           ^
           ==
myFunc.cpp:281:13: error: use of undeclared identifier '_popen'; did you mean
      'popen'?
            _popen(command.c_str(), "r");
            ^~~~~~
            popen
/usr/include/stdio.h:325:7: note: 'popen' declared here
FILE    *popen(const char *, const char *) __DARWIN_ALIAS_STARTING(__MAC...
         ^
myFunc.cpp:289:5: error: use of undeclared identifier '_pclose'; did you mean
      'pclose'?
                                _pclose(stream);
                                ^~~~~~~
                                pclose
/usr/include/stdio.h:321:6: note: 'pclose' declared here
int      pclose(FILE *) __swift_unavailable_on("Use posix_spawn APIs or ...
         ^
myFunc.cpp:309:5: error: use of undeclared identifier '_popen'; did you mean
      'popen'?
                                _popen(command.c_str(), "r");
                                ^~~~~~
                                popen
/usr/include/stdio.h:325:7: note: 'popen' declared here
FILE    *popen(const char *, const char *) __DARWIN_ALIAS_STARTING(__MAC...
         ^
myFunc.cpp:318:5: error: use of undeclared identifier '_pclose'; did you mean
      'pclose'?
                                _pclose(stream);
                                ^~~~~~~
                                pclose
/usr/include/stdio.h:321:6: note: 'pclose' declared here
int      pclose(FILE *) __swift_unavailable_on("Use posix_spawn APIs or ...
         ^
myFunc.cpp:357:5: error: use of undeclared identifier '_popen'; did you mean
      'popen'?
                                _popen(command.c_str(), "r");
                                ^~~~~~
                                popen
/usr/include/stdio.h:325:7: note: 'popen' declared here
FILE    *popen(const char *, const char *) __DARWIN_ALIAS_STARTING(__MAC...
         ^
myFunc.cpp:370:26: warning: using the result of an assignment as a condition
      without parentheses [-Wparentheses]
                if (toadd=strccnt(strs[4].c_str(), '^')) {
                    ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
myFunc.cpp:370:26: note: place parentheses around the assignment to silence this
      warning
                if (toadd=strccnt(strs[4].c_str(), '^')) {
                         ^
                    (                                  )
myFunc.cpp:370:26: note: use '==' to turn this assignment into an equality
      comparison
                if (toadd=strccnt(strs[4].c_str(), '^')) {
                         ^
                         ==
myFunc.cpp:377:5: error: use of undeclared identifier '_pclose'; did you mean
      'pclose'?
                                _pclose(stream);
                                ^~~~~~~
                                pclose
/usr/include/stdio.h:321:6: note: 'pclose' declared here
int      pclose(FILE *) __swift_unavailable_on("Use posix_spawn APIs or ...
         ^
myFunc.cpp:393:26: warning: using the result of an assignment as a condition
      without parentheses [-Wparentheses]
                if (toadd=strccnt(strs[4].c_str(), '^')) {
                    ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
myFunc.cpp:393:26: note: place parentheses around the assignment to silence this
      warning
                if (toadd=strccnt(strs[4].c_str(), '^')) {
                         ^
                    (                                  )
myFunc.cpp:393:26: note: use '==' to turn this assignment into an equality
      comparison
                if (toadd=strccnt(strs[4].c_str(), '^')) {
                         ^
                         ==
3 warnings and 6 errors generated.
make[1]: *** [myFunc.o] Error 1
make: *** [all] Error 2

**Comment by sambrightman** [comment]
See #10

**Comment by valeu** [comment]
Thank you, Sam, and I advice using v10.3.

**Comment by valeu** [comment]
Does the latest version also generate errors?
https://github.com/BoevaLab/FREEC/archive/master.zip
or clone from https://github.com/BoevaLab/FREEC.git

**Comment by krsachin** [comment]
v10.3 also generate same error.

**Comment by krsachin** [comment]
Thanks!! 
v10.3 is working.
