### ISSUE TITLE
 expalinations for makeGraph.R output

### ISSUE THREAD

**Issue by hongenxu** [BoevaLab/FREEC#18]
Hi, 

It's great to provide such a script for visualization. Would you please provide some explanations, especially for BAF plot (different color lines, dots)?

Best regards,
Hongen

**Comment by valeu** [comment]
Orange corresponds to AB or AA/BB regions
Blue - to everything else.
Black lines - inferred BAF (adjusted for contamination by normal cells), purple - evaluated BAF (including contamination)

**Comment by hongenxu** [comment]
thanks.
