### ISSUE TITLE
Warning: minimal recommended polynomial degree for "ReadCount ~ GC-content" is 3

### ISSUE THREAD

**Issue by igordot** [BoevaLab/FREEC#19]
I am getting the following warning:
```
..Polynomial degree for "ReadCount ~ GC-content" is 1
Warning: minimal recommended polynomial degree for "ReadCount ~ GC-content" is 3
Comment or remove the corresponding line in the config file to try both degree==3 and degree==4
```
However, the documentation states:
```
Default: 3&4 (GC-content based normalization, WGS) or 1 (control-read-count-based normalization, WES)
```
I set `forceGCcontentNormalization` to 1 as the documentation suggests for WES. That might be triggering the warning, since that is forcing GC-content normalization.

So what is the right combination to use for WES?

**Comment by valeu** [comment]
Dear Igor,
The best way to proceed is to comment #degree and #forceGCcontentNormalization to make FREEC decide itself on the best parameters. In the case of WES it will do two normalization steps (GC, then Control) so it should first use degree 3&4 and then 1. I hope it is what really happens. But I will check again.

**Comment by valeu** [comment]
Also, please use the very latest version of Control-FREEC.

**Comment by igordot** [comment]
I didn't realize FREEC can decide itself on the best parameters. I was just trying to follow the documentation suggestions. I'll try without setting degree and forceGCcontentNormalization as you recommend.

I am using the latest v10.6.
