### ISSUE TITLE
amplicon data

### ISSUE THREAD

**Issue by yiliu4234** [BoevaLab/FREEC#22]
Hello  I am trying to use FREE-C software for finding CNVs in amplicon sequencing data. I used pileup format as matefile ,both control and sample are pile up format , but I get error  when it calculate BAF file

..use "pileup" format of reads to calculate BAF profiles
..Starting reading /home/ywliao/project/Gengyan/mpileup/pileup/spileup/wbcpileup/health1.pileup to calculate BAF profiles
段错误(吐核)

Please help me

**Comment by valeu** [comment]
Dear Yi Lui,
Please send me your config and the complete output?

**Comment by yiliu4234** [comment]
OK !
[config_cervical.txt](https://github.com/BoevaLab/FREEC/files/1012939/config_cervical.txt)

![Uploading Screenshot from 2017-05-19 10-19-00.png…]()
There are not files in Outputdir 
Thanks !

**Comment by valeu** [comment]
Dear Yi Lui, 
your config file seems OK to me. However, I need to see the complete output of FREEC into the command line.

**Comment by yiliu4234** [comment]
This is output .
[stdout.txt](https://github.com/BoevaLab/FREEC/files/1015844/stdout.txt)
Thanks very much !

**Comment by valeu** [comment]
It looks that you very few genes. In this case, you may consider using OncoCNV developed for amplicon-seq data.

If you want to run FREEC, I suggest that you exclude all chromosomes not present in your .bed file from the file with chromosome lengths.

**Comment by yiliu4234** [comment]
Following your steps, I succeeded in running FREEC, thank you  very much !
