### ISSUE TITLE
support for CRAM files through samtools

### ISSUE THREAD

**Issue by matthdsm** [BoevaLab/FREEC#23]
Hi,

Would it be possible to include support for CRAM compressed files through samtools?
If I'm not mistaking, this is already native to the latest samtools/HTSlib

Cheers
M

**Comment by valeu** [comment]
Supporting CRAM is not planned in the nearest future. Please transform you CRAM to BAM to run FREEC.
Also, you can modify the code yourself to add the CRAM support and pull.
