### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by michelatebaldi** [BoevaLab/FREEC#27]
Hi,
I tried to run freec with this config file to analyze WGS data without control.

[general]
chrLenFile = /home/data/resources/gatk_resources/hg19/ucsc.hg19.fasta.fai
chrFiles = /home/data/analysis/CTC/FREEC/files/hg19/ 
gemMappabilityFile = /home/data/analysis/CTC/FREEC/files/GEM_mappability/hg19/out76_hg19.gem

minCNAlength = 1
coefficientOfVariation = 0.06
printNA = FALSE
maxThreads = 4
sex = XX
uniqueMatch = TRUE
ploidy = 4
outputDir = /home/data/analysis/CTC/FREEC/FREEC-11.0/data/IonXpress_008/support/gem76/
BedGraphOutput = TRUE

[sample]
mateFile = /home/data/runs/Archivio/da_archiviare/Ampli1_LowPass_01/IonXpress_008_R_2017_06_08_13_23_10_user_SN2-41-Pietro_LowPass_prova_Auto_user_SN2-41-Pietro_LowPass_prova_91.bam
inputFormat = BAM
mateOrientation = 0

The software returned this error at this step:

Number of EM iterations :18
root mean square error = 11.5541
Y = -11482.7*x^4+56229.2*x^3+-69675.9*x^2+32512.7*x^1+-4982.38
Errore di segmentazione (core dumped)

Could you help me please??

Thanks,
Michela.

**Comment by michelatebaldi** [comment]
Problem solved changing the chrLenFile.

**Comment by yueyangtime** [comment]
hi,
from where can download the 'gemMappabilityFile'?
thanks,
yueyang
