### ISSUE TITLE
"*ratio.txt"file question ?

### ISSUE THREAD

**Issue by fengdong110** [BoevaLab/FREEC#28]
Hello dear friend :

    I don't know the  *ratio.txt file Ratio column equal to -1 meaning  what。

  My result is like ：
![image](https://user-images.githubusercontent.com/19946295/30411536-093fa280-9944-11e7-8e5d-80e3e632c074.png)
  My sample have a chr13 CNV. But through the result graph I can't see it.

I'm very much looking forward to your recovery.
Thank you very much !

**Comment by fengdong110** [comment]
Maybe I know the reason.  it is "unknown" region.

**Comment by valeu** [comment]
-1 means that the information is not available. For instance, there is not (enough) reads mapping to these regions.

See also http://boevalab.com/FREEC/FAQ.html  - Q6.

**Comment by fengdong110** [comment]
ok !  Thank you very much !

**Comment by qins** [comment]
@valeu Not enough reads may also means deletion

**Comment by valeu** [comment]
"not enough reads" in the control sample if it is used
