### ISSUE TITLE
Warning: control length is not equal to the sample length for chromosome M

### ISSUE THREAD

**Issue by moshl** [BoevaLab/FREEC#34]
Dear stuff in Boevalab,
  I am in trouble when i run freec to analysis my WGS data. The problems is :

"Warning: control length is not equal to the sample length for chromosome M
Segmentation fault (core dumped)"

I check the output (cpn) after failed,  the segment of chrM in sample is similar with in control. I am confused, i donnot know how to solve it. Looking forward to your reply!

bestwishes,
moshl

**Comment by valeu** [comment]
Please check that you use the right genome assembly.

**Comment by moshl** [comment]
I use the hg19 and cannot change the genome assembly during the process,like bwa, BQSR, freec etc. It is ok to analysis CNV of  some other WGS data using freec and the genome assembly before .

**Comment by valeu** [comment]
can you just remove chrM from your chromosome length file?

**Comment by moshl** [comment]
Adding a parameter: mateCopyNumberFile , this problem is solved. But i dunno, can you give some explain?

attachement
updated parts of the config file
"[sample]
mateCopyNumberFile=/pnas/liuxin_group/moshl/NR_yangjy/Results/Freec/WY/3D30/WY_3D30.mpileup_sample.cpn
mateFile = /pnas/liuxin_group/moshl/NR_yangjy/Results/Varscan/WY/WY_3D30.mpileup
inputFormat = pileup
mateOrientation = FR

[control]
mateCopyNumberFile=/pnas/liuxin_group/moshl/NR_yangjy/Results/Freec/WY/3D30/WY_CTRL.mpileup_control.cpn
mateFile = /pnas/liuxin_group/moshl/NR_yangjy/Results/Varscan/WY/WY_CTRL.mpileup
inputFormat = pileup
mateOrientation = FR"

**Comment by valeu** [comment]
I do not know what happened. It can be related to differences in length of chrM in different genome builds.. But I am not sure
