### ISSUE TITLE
Exome-seq Copy number analysis

### ISSUE THREAD

**Issue by kgaonkar6** [BoevaLab/FREEC#38]
Hello, 

Can you please confirm if we can run exome-seq data through FREEC without a paired normal? In the documentation you've mentioned that "Starting from Control-FREEC v10.6, Control-FREEC can work on exome-seq data without a control sample"  

The tasks ran into completion but I also got the following warnings:
WARNING: You did not provide a control sample ('mateFile' or 'mateCopyNumberFile') but you are working with targeted sequencing data that has a capture bias.
WARNING: Will proceed without any normalization (on your own risk)!!
Warning : You did not provide a control sample for WES data. No normalization will be applied to read counts!

Thanks!

**Comment by valeu** [comment]
Technically FREEC will work: it will only normalize the data for the GC-content bias. The profiles will be smooth if there is no much capture bias in your protocol. It can be your case or not.. Have to try if you do not have a control sample.
