### ISSUE TITLE
FREEC was not able to extract reads

### ISSUE THREAD

**Issue by huangl07** [BoevaLab/FREEC#39]
dear Freec support：

my data is not human database.

my config file is 
###For more options see: http://boevalab.com/FREEC/tutorial.html#CONFIG ###

[general]

##parameters chrLenFile and ploidy are required.

chrLenFile = /mnt/ilustre/users/minghao.zhang/newmdt/Project/MJ20180427034_zhujingle/variant_20180531/02.ref-config/ref.fa.fai
ploidy = 2

##Parameter "breakPointThreshold" specifies the maximal slope of the slope of residual sum of squares. 
##This should be a positive value. The closer it is to Zero, the more breakpoints will be called. Its recommended value is between 0.01 and 0.08.

breakPointThreshold = .8

##Either coefficientOfVariation or window must be specified for whole genome sequencing data. Set window=0 for exome sequencing data.

#coefficientOfVariation = 0.01
window = 50000
#step=10000

##Either chrFiles or GCcontentProfile must be specified too if no control dataset is available. 
##If you provide a path to chromosome files, Control-FREEC will look for the following fasta files in your directory (in this order): 
##1, 1.fa, 1.fasta, chr1.fa, chr1.fasta; 2, 2.fa, etc.
## Please ensure that you don't have other files but sequences having the listed names in this directory. 
chrFiles = /mnt/ilustre/users/minghao.zhang/newmdt/Project/MJ20180427034_zhujingle/variant_20180531/02.ref-config/
#GCcontentProfile = test/GC_profile_50kb.cnp

##if you are working with something non-human, we may need to modify these parameters:
#minExpectedGC = 0.35
#maxExpectedGC = 0.55

#readCountThreshold=10

numberOfProcesses = 4
outputDir = /mnt/ilustre/users/long.huang/freec/
#contaminationAdjustment = TRUE
#contamination = 0.4
#minMappabilityPerWindow = 0.95

##If the parameter gemMappabilityFile is not specified, then the fraction of non-N nucleotides per window is used as Mappability.

#gemMappabilityFile = /GEM_mappability/out76.gem

#breakPointType = 4
#forceGCcontentNormalization = 0
#sex=XY

##set BedGraphOutput=TRUE if you want to create a BedGraph track for visualization in the UCSC genome browser:
#BedGraphOutput=TRUE

[sample]

mateFile = /mnt/ilustre/users/minghao.zhang/newmdt/Project/MJ20180427034_zhujingle/variant_20180531/04.bam-sort/Red.sort.bam
inputFormat = BAM
matesOrientation=0

##use "mateOrientation=0" for sorted .SAM and .BAM

[control]
#mateFile = /path/control.pileup.gz
#mateCopyNumberFile = path/control.cpn
#inputFormat = pileup

#mateOrientation = RF

#[BAF]

##use the following options to calculate B allele frequency profiles and genotype status. This option can only be used if "inputFormat=pileup"

#SNPfile = /bioinfo/users/vboeva/Desktop/annotations/hg19_snp131.SingleDiNucl.1based.txt
#minimalCoveragePerPosition = 5

##use "minimalQualityPerPosition" and "shiftInQuality" to consider only high quality position in calculation of allelic frequencies (this option significantly slows down re

#minimalQualityPerPosition = 5
#shiftInQuality = 33

[target]

##use a tab-delimited .BED file to specify capture regions (control dataset is needed to use this option):

#captureRegions = /bioinfo/users/vboeva/Desktop/testChr19/capture.bed

my error is
Control-FREEC v11.3 : a method for automatic detection of copy number alterations, subclones and for accurate estimation of contamination and main ploidy using deep-sequencing data
Non Multi-threading mode
..Breakpoint threshold for segmentation of copy number profiles is 0.8
..telocenromeric set to 50000
..FREEC is not going to output normalized copy number profiles into a BedGraph file (for example, for visualization in the UCSC GB). Use "[general] BedGraphOutput=TRUE" if you want a BedGraph file
..FREEC is not going to adjust profiles for a possible contamination by normal cells
..Window = 50000 was set
..Output directory:	/mnt/ilustre/users/long.huang/freec/
..Directory with files containing chromosome sequences:	/mnt/ilustre/users/minghao.zhang/newmdt/Project/MJ20180427034_zhujingle/variant_20180531/02.ref-config/
..Sample file:	/mnt/ilustre/users/minghao.zhang/newmdt/Project/MJ20180427034_zhujingle/variant_20180531/04.bam-sort/Red.sort.bam
..Sample input format:	BAM
..will use this instance of samtools: 'samtools' to read BAM files
..minimal expected GC-content (general parameter "minExpectedGC") was set to 0.35
..maximal expected GC-content (general parameter "maxExpectedGC") was set to 0.55
..Polynomial degree for "ReadCount ~ GC-content" normalization is 3 or 4: will try both
..Minimal CNA length (in windows) is 1
..File with chromosome lengths:	/mnt/ilustre/users/minghao.zhang/newmdt/Project/MJ20180427034_zhujingle/variant_20180531/02.ref-config/ref.fa.fai
..Using the default minimal mappability value of 0.85
..uniqueMatch = FALSE
..average ploidy set to 2
..break-point type set to 2
..noisyData set to 0
..Control-FREEC will not look for subclones
..File /mnt/ilustre/users/minghao.zhang/newmdt/Project/MJ20180427034_zhujingle/variant_20180531/02.ref-config/ref.fa.fai was read
..Starting reading /mnt/ilustre/users/minghao.zhang/newmdt/Project/MJ20180427034_zhujingle/variant_20180531/04.bam-sort/Red.sort.bam
..samtools should be installed to be able to read BAM files; will use the following command for samtools: samtools view /mnt/ilustre/users/minghao.zhang/newmdt/Project/MJ20180427034_zhujingle/variant_20180531/04.bam-sort/Red.sort.bam
..finished reading /mnt/ilustre/users/minghao.zhang/newmdt/Project/MJ20180427034_zhujingle/variant_20180531/04.bam-sort/Red.sort.bam
PROFILING [tid=47383814016416]: /mnt/ilustre/users/minghao.zhang/newmdt/Project/MJ20180427034_zhujingle/variant_20180531/04.bam-sort/Red.sort.bam read in 835 seconds [fillMyHash]
124465060 lines read..
0 reads used to compute copy number profile

Error: FREEC was not able to extract reads from /mnt/ilustre/users/minghao.zhang/newmdt/Project/MJ20180427034_zhujingle/variant_20180531/04.bam-sort/Red.sort.bam

Check your parameters: inputFormat and matesOrientation
Use "matesOrientation=0" if you have single end reads
Check the list of possible input formats at http://bioinfo-out.curie.fr/projects/freec/tutorial.html#CONFIG

my bam is PE sort bam by samtools

thank you

**Comment by valeu** [comment]
please share 

`head /mnt/ilustre/users/minghao.zhang/newmdt/Project/MJ20180427034_zhujingle/variant_20180531/02.ref-config/ref.fa.fai`

`samtools view /mnt/ilustre/users/minghao.zhang/newmdt/Project/MJ20180427034_zhujingle/variant_20180531/04.bam-sort/Red.sort.bam | head`

`ls /mnt/ilustre/users/minghao.zhang/newmdt/Project/MJ20180427034_zhujingle/variant_20180531/02.ref-config/`

**Comment by huangl07** [comment]
sorry,I forget

head is

sca1	8941109	6	8941109	8941110
sca2	25231442	8941122	25231442	25231443
sca3	5635278	34172571	5635278	5635279
sca4	9643118	39807856	9643118	9643119
sca5	16802859	49450981	16802859	16802860
sca6	10603851	66253847	10603851	10603852
sca7	10558286	76857705	10558286	10558287
sca8	4843466	87415998	4843466	4843467
sca9	3637106	92259471	3637106	3637107
sca10	7660908	95896585	7660908	7660909

bam is 

ST-E00575:209:HJMMHCCXY:5:1116:18528:69098	371	sca1	165	0	11H140M	sca207196	3572	0	*	*	NM:i:5	MD:Z:57G8G0G63T2A5	MC:Z:77M74H	AS:i:116	RG:Z:1
ST-E00575:209:HJMMHCCXY:5:1214:8460:24233	163	sca1	1347	0	151M	=	1555	359	AAAATTTCCAAACAAATGATACTTCCAACTATACTCCTCATCAAAAAACTCCCCATCACTCACATTCTCTCTCCTCCTCTCTCTCTCTACCCTCTCAAGAACACCCTTCACCGCCAGGTCAAAAGCGTCCTCCACCGCCTCCAGCCGCCGT	AAFFFJJJJJJJJJJFJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJFJJJAJ<JFJJJJJJJJJJFJJJJJJJJFJJFJJJJJJ<FJJJJFFF<FJJAJAJJJJJJJJJJJJJJ<FJJ7F<<JJJ-	NM:i:1	MD:Z:54G96	MC:Z:151M	AS:i:146	XS:i:146	RG:Z:1
ST-E00575:209:HJMMHCCXY:5:2222:23906:19733	99	sca1	1387	0	151M	=	1583	347	TCAAAAAACTCCCCATCACTCACATTCTCTCTCCTCCTCTCTCTCTCTACCCTCTCAAGAACACCCTTCACCGCCAGGTCAAAAGCGTCCTCCACCGCCTCCAGCCGCCGTGATCTGGGGTCGGCGTAAACCACCTTCGGAATCAGCTTTA	AAFFFJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJAJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJ7FFJJJJJAJJJJJJJJJJJJJJJJJJJJJF	NM:i:1	MD:Z:14G136	MC:Z:151M	AS:i:146	XS:i:146	RG:Z:1
ST-E00575:209:HJMMHCCXY:5:1218:11820:38983	163	sca1	1402	27	151M	=	1876	625	TCACTCACATTCTCTCTCCTCCTCTCTCTCTCTACCCTCTCAAGAACACCCTTCACCGCCAGGTCAAAAGCGTCCTCCACCGCCTCCAGCCGCCGTGATCTGGGGTCGGCGTAAACCACCTTCGGAATCAGCTTTATCACCTCCTCTCTCA	AAA<FJJJJJJJJJJJJJJJJFJJFJJJJJJJJFJJJJJJJAJ<JJJJJJJJJJ<JJJJJA-A-A<AA-AAA<JJJJJJFJJJJJFJAAJJJJJJAJ-7AAA7FF7FJJJJ<J7JFF<-<<<F777<<<7-F--<<JA7-<FJFFJ7A-<-	NM:i:0	MD:Z:151	MC:Z:151M	AS:i:151	XS:i:151	RG:Z:1
ST-E00575:209:HJMMHCCXY:5:1214:8460:24233	83	sca1	1555	0	151M	=	1347	-359	GCCGTTATCCTCGCCCTAGAAACCCTAGACAACACCCTCTCGATGCTGACCCTCTTCCCCTTCACGTCGTCCTCCGGTATCAGAATGGAGTACTTGAAGAAATCACGGGGGAGGTGCCAGAGATACTGCACGTAGGCGGATCCCGGCGTGA	JJJJJFJJJJJJJJJJA<FAJAJJJJ<J<F<AJ-JJJJJJJJJJJJFJFJJJFJJJJJJJJJJFJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFAA	NM:i:1	MD:Z:17G133	MC:Z:151M	AS:i:146	XS:i:146	RG:Z:1
ST-E00575:209:HJMMHCCXY:5:1106:27093:20436	99	sca1	1572	0	151M	=	1860	435	AGAAACCCTAGACAACACCCTCTCGATGCTGACCCTCTTCCCCTTCACGTCGTCCTCCGGTATCAGAATGGAGTACTTGAAGAAATCACGGGGGAGGTGCCAGAGATACTGCACGTAGGCGGATCCCGGCGTGAAAAACACCGGTATACAG	AA<FFJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFJJJJJJJJJJJAFFJJJJJJJJJJJJFJJJJJ<J-FJJJJJJJFJJJJJJJJJJJJJJJJFJJJJJJJJJFFJFFJJJJJJFFFJJJFA	NM:i:1	MD:Z:0G150	MC:Z:147M	AS:i:150	XS:i:150	RG:Z:1
ST-E00575:209:HJMMHCCXY:5:1106:26880:20454	99	sca1	1572	0	151M	=	1856	435	AGAAACCCTAGACAACACCCTCTCGATGCTGACCCTCTTCCCCTTCACGTCGTCCTCCGGTATCAGAATGGAGTACTTGAAGAAATCACGGGGGAGGTGCCAGAGATACTGCACGTAGGCGGATCCCGGCGTGAAAAACACCGGTATACAG	AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJFJFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJA	NM:i:1	MD:Z:0G150	MC:Z:151M	AS:i:150	XS:i:150	RG:Z:1
ST-E00575:209:HJMMHCCXY:5:2204:28737:34324	163	sca1	1575	0	151M	=	1802	378	AACCCTAGACAACACCCTCTCGATGCTGACCCTCTTCCCCTTCACGTCGTCCTCCGGTATCAGAATGGAGTACTTGAAGAAATCACGGGGGAGGTGCCAGAGATACTGCACGTAGGCGGATCCCGGCGTGAAAAACACCGGTATACAGCCA	AAAFFFJFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFJJJJJFJJJJFFFJJFJJFJJJJ<JFAFJFFFFJ-FFJJJJJJJJJF7JJJJJ<A<77F<FJJFFJFFJJJF<FAAJJFJJ-AJ-7----FFFJA)<<AF<FF)	NM:i:1	MD:Z:150G0	MC:Z:151M	AS:i:150	XS:i:150	RG:Z:1
ST-E00575:209:HJMMHCCXY:5:2222:23906:19733	147	sca1	1583	0	151M	=	1387	-347	ACAACACCCTCTCGATGCTGACCCTCTTCCCCTTCACGTCGTCCTCCGGTATCAGAATGGAGTACTTGAAGAAATCACGGGGGAGGTGCCAGAGATACTGCACGTAGGCGGATCCCGGCGTGAAAAACACCGGTATACAGCCAGCGAGTAT	AF-<AAJFAF<-JJJJFJFJ<JJJAAA<JJJJF7JJJJJJFFFF7JJFJFFAFJJJFJJJFJJJJJJJJJJJFFFAJJJJJJJFJJFJJJJAJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFAJJJJJJJJJJJJJJFJJJFFFFAA	NM:i:1	MD:Z:142G8	MC:Z:151M	AS:i:146	XS:i:146	RG:Z:1
ST-E00575:209:HJMMHCCXY:5:1205:19116:67937	99	sca1	1615	0	151M	=	1808	344	TTCACGTCGTCCTCCGGTATCAGAATGGAGTACTTGAAGAAATCACGGGGGAGGTGCCAGAGATACTGCACGTAGGCGGATCCCGGCGTGAAAAACACCGGTATACAGCCAGCGAGTATGGAGTCGAAAGTTGATCGGCGGGTGTAGGAAT	AAFFFJJJJJJJJJJJJAAJJJFJJJJJJJJJJJJJJJJJJFJJJJJJJJJFJFJJJ-FJJFJJJJJJJJJJJJJJAJJ<JJJJJJJJJJJJJJJJJJJJJFAJJJJJJJJJJJJJ<FJJJ<AFJJJJFJFJJJJJFJFJJJJJJJAJJF<	NM:i:1	MD:Z:110G40	MC:Z:151M	AS:i:146	XS:i:146	RG:Z:1


config is
###For more options see: http://boevalab.com/FREEC/tutorial.html#CONFIG ###


[general]

##parameters chrLenFile and ploidy are required.

chrLenFile = /mnt/ilustre/users/minghao.zhang/newmdt/Project/MJ20180427034_zhujingle/variant_20180531/02.ref-config/ref.fa.fai
ploidy = 2


##Parameter "breakPointThreshold" specifies the maximal slope of the slope of residual sum of squares. 
##This should be a positive value. The closer it is to Zero, the more breakpoints will be called. Its recommended value is between 0.01 and 0.08.

breakPointThreshold = .8


##Either coefficientOfVariation or window must be specified for whole genome sequencing data. Set window=0 for exome sequencing data.

#coefficientOfVariation = 0.01
window = 50000
#step=10000

##Either chrFiles or GCcontentProfile must be specified too if no control dataset is available. 
##If you provide a path to chromosome files, Control-FREEC will look for the following fasta files in your directory (in this order): 
##1, 1.fa, 1.fasta, chr1.fa, chr1.fasta; 2, 2.fa, etc.
## Please ensure that you don't have other files but sequences having the listed names in this directory. 
chrFiles = /mnt/ilustre/users/long.huang/freec/sca
#GCcontentProfile = test/GC_profile_50kb.cnp


##if you are working with something non-human, we may need to modify these parameters:
#minExpectedGC = 0.35
#maxExpectedGC = 0.55


#readCountThreshold=10

numberOfProcesses = 4
outputDir = /mnt/ilustre/users/long.huang/freec/
#contaminationAdjustment = TRUE
#contamination = 0.4
#minMappabilityPerWindow = 0.95


##If the parameter gemMappabilityFile is not specified, then the fraction of non-N nucleotides per window is used as Mappability.

#gemMappabilityFile = /GEM_mappability/out76.gem


#breakPointType = 4
#forceGCcontentNormalization = 0
#sex=XY

##set BedGraphOutput=TRUE if you want to create a BedGraph track for visualization in the UCSC genome browser:
#BedGraphOutput=TRUE

[sample]

mateFile = /mnt/ilustre/users/minghao.zhang/newmdt/Project/MJ20180427034_zhujingle/variant_20180531/03.bwa-mapping/Red.b1.bam
inputFormat = BAM
matesOrientation=RF

##use "mateOrientation=0" for sorted .SAM and .BAM

[control]

#mateFile = /path/control.pileup.gz
#mateCopyNumberFile = path/control.cpn
#inputFormat = pileup


#mateOrientation = RF

#[BAF]

##use the following options to calculate B allele frequency profiles and genotype status. This option can only be used if "inputFormat=pileup"

#SNPfile = /bioinfo/users/vboeva/Desktop/annotations/hg19_snp131.SingleDiNucl.1based.txt
#minimalCoveragePerPosition = 5

##use "minimalQualityPerPosition" and "shiftInQuality" to consider only high quality position in calculation of allelic frequencies (this option significantly slows down reading of .pileup)

#minimalQualityPerPosition = 5
#shiftInQuality = 33

[target]

##use a tab-delimited .BED file to specify capture regions (control dataset is needed to use this option):

#captureRegions = /bioinfo/users/vboeva/Desktop/testChr19/capture.bed


thank you

**Comment by valeu** [comment]
and `ls /mnt/ilustre/users/long.huang/freec/sca` ?

**Comment by huangl07** [comment]
sorry，my sca dir is a dir contain all scaffold data

I split my chrlist by chrid

like /mnt/ilustre/users/long.huang/freec/sca/sca1.fa  /mnt/ilustre/users/long.huang/freec/sca/sca2.fa

**Comment by valeu** [comment]
I have fixed a bug that prevented reading your .fai file. It should be OK with version 11.5.
BTW, your reads are FR and not RF as you state in the config file.

Use  `mateOrientation=FR` instead of  `matesOrientation=RF`
And there is not difference whether to use 's' or not after "mate" for the config file parser starting from v11.5.

**Comment by biocodeworld** [comment]
I got the same error and did everything kindly look at it: shreya@LAPTOP-0DAP9OJB:~$ freec -conf /home/shreya/sample_freec_config.txt
Control-FREEC v11.6 : a method for automatic detection of copy number alterations, subclones and for accurate estimation of contamination and main ploidy using deep-sequencing data
Multi-threading mode using 4 threads
..Breakpoint threshold for segmentation of copy number profiles is 0.8
..telocenromeric set to 50000
..FREEC is not going to adjust profiles for a possible contamination by normal cells
..Window = 50000 was set
..Step: 10000
..Output directory:     /home/shreya/freec_output
..Directory with files containing chromosome sequences: /home/shreya/genomes/hg38_chromosomes/
..Sample file:  /home/shreya/sample_wgs_alignment_results/SRR33503083_aligned_output.sorted.bam
..Sample input format:  BAM
..will use this instance of samtools: 'samtools' to read BAM files
..minimal expected GC-content (general parameter "minExpectedGC") was set to 0.35
..maximal expected GC-content (general parameter "maxExpectedGC") was set to 0.55
..Polynomial degree for "ReadCount ~ GC-content" normalization is 3 or 4: will try both
..Minimal CNA length (in windows) is 3
..File with chromosome lengths: /home/shreya/GRCH38/ncbi_dataset/data/GCF_000001405.26/modified_GRCh38_genomic.fna.fai
..Using the default minimal mappability value of 0.85
..uniqueMatch = FALSE
..average ploidy set to 2
..break-point type set to 4
..noisyData set to 0
..Control-FREEC will not look for subclones
..File /home/shreya/GRCH38/ncbi_dataset/data/GCF_000001405.26/modified_GRCh38_genomic.fna.fai was read
..[genomecopynumber] Starting reading /home/shreya/sample_wgs_alignment_results/SRR33503083_aligned_output.sorted.bam
..samtools should be installed to be able to read BAM files; will use the following command for samtools: samtools view -@ 4 /home/shreya/sample_wgs_alignment_results/SRR33503083_aligned_output.sorted.bam
..finished reading /home/shreya/sample_wgs_alignment_results/SRR33503083_aligned_output.sorted.bam
PROFILING [tid=140325480134464]: /home/shreya/sample_wgs_alignment_results/SRR33503083_aligned_output.sorted.bam read in 0 seconds [fillMyHash]
489020 lines read..
0 reads used to compute copy number profile

Error: FREEC was not able to extract reads from /home/shreya/sample_wgs_alignment_results/SRR33503083_aligned_output.sorted.bam

Check your parameters: inputFormat and mateOrientation
Use "matesOrientation=0" if you have single end reads
Check the list of possible input formats at http://bioinfo-out.curie.fr/projects/freec/tutorial.html#CONFIG
