### ISSUE TITLE
recommended value for breakPointThreshold

### ISSUE THREAD

**Issue by hongenxu** [BoevaLab/FREEC#4]
Hi, 

in the version of FREEC-9.6, there is a file config_WGS.txt. In it, we can see following text
"
##This should be a positive value. The closer it is to Zero, the more breakpoints will be called. Its recommended value is between 0.01 and 0.08.
breakPointThreshold = .8"

I also checked http://boevalab.com/FREEC/tutorial.html#CONFIG, the default value for breakPointThreshold  is 0.8. 

Are 0.01 and 0.08 should be 0.1 and 0.8? 

Best regards,
Hongen

**Comment by valeu** [comment]
You are right, 0.01 will give too many breakpoints. I should have written that OK values lay between 0.6 and 1.2.
