### ISSUE TITLE
Error on duplicated target regions

### ISSUE THREAD

**Issue by jenzopr** [BoevaLab/FREEC#43]
Dear Valentina,

when running FREEC (v11.4), I currently get an error because of potentially duplicated target regions.
Here is what part of the output looks like:

```
..Starting reading bam/***.bam
..sambamba should be installed to be able to read BAM files; will use the following command for sambamba: sambamba view -t 30 bam/***.bam
..finished reading bam/***.bam
PROFILING [tid=140085019785024]: bam/***.bam read in 3309 seconds [fillMyHash]
77240649 lines read..
57024716 reads used to compute copy number profile
printing counts into cnvs/***.bam_control.cpn
..Will not consider chrY..
..Erased chrY from the list of chromosomes
..FREEC will take into account only regions from agilent_SureSelect/S07604624_Covered.hg38_whitelist_unique.bed
..using GC-content to normalize copy number profiles
Error: your BED file with coordinates of targeted regions may contain duplicates
Check chromosome 1
```

I already tried to resolve duplicated entries by running
```
sort -k1,1 -k2,2n -k3,3n -u 
```
on the target regions bed file, but the error persists. How does FREEC determine a *unique* set of target regions? Is the strand important as well?

Best and thanks, 
Jens

P.S.: Here is the configuration I used:
```
[general]
minCNAlength = 3
printNA = FALSE
maxThreads = 30
minimalSubclonePresence = 100
noisyData = TRUE
BedGraphOutput = TRUE
chrFiles = /mnt/flatfiles/organisms/human/hg38_GRCh38/chromosomes/
sambamba = sambamba
breakPointThreshold = 1.2
ploidy = 2
sex = XX
breakPointType = 4
window = 0
chrLenFile = chrNameLength.txt
readCountThreshold = 50
outputDir = cnvs
[sample]
inputFormat = BAM
mateOrientation = FR
mateFile = bam/***.bam
[control]
inputFormat = BAM
mateOrientation = 0
mateFile = bam/***.bam
[BAF]
fastaFile = /mnt/flatfiles/organisms/human/hg38_GRCh38/indices/star_GRCh38_gencode.v27/Homo_sapiens.GRCh38.27.dna_sm.toplevel.fa
[target]
captureRegions = agilent_SureSelect/S07604624_Covered.hg38_whitelist_unique.bed
```

**Comment by valeu** [comment]
Dear Jens,

You regions should have different starts and ends, but they can overlap. The strand is not important. 
You can share agilent_SureSelect/S07604624_Covered.hg38_whitelist_unique.bed with me if you cannot figure out what is going on.

Valentina

**Comment by jenzopr** [comment]
Hi Valentina,

thanks, that's great! You'll find the file [here](https://bioinformatics.mpi-bn.mpg.de/static/S07604624_Covered.hg38_whitelist_unique.bed). 

Jens

**Comment by valeu** [comment]
Your file looks good. I do not know what goes wrong. Can you share your input files, please?
Do not have to share the whole .bam, just a subsample:
`samtools view -s 0.1 -b bam/***.bam > bam/***_subsample.0.1.bam`

**Comment by jenzopr** [comment]
Sure, the subsample is available from [here!](https://bioinformatics.mpi-bn.mpg.de/static/subsample.bam) 
Thank you a lot for your effort!! Highly appreciated ☺️

**Comment by valeu** [comment]
The problem was caused by these two lines:
```
chr1	16565583	16565773	ref|NBPF10,ref|...
chr1	16565583	16565834	ref|NBPF1,ref|...
```
or
```
chr1	120823989	120824207	ref|NBPF8,ref...
chr1	120823989	120824216	ref|NBPF8,ref|...
```

The first position is the same, so FREEC thinks that there are duplicate regions in your .bed file.
You may try to change the second lines by adding 1 to 
`chr1	16565583	16565834	ref|NBPF1,ref|...`
to make it work. Or just remove the first lines.

**Comment by jenzopr** [comment]
I see! I thought these are *overlapping* regions. I'll just do a `bedtools merge` on the regions, this should be fine. It anyway makes sense to merge the target regions for Exome-Seq.

Best and thanks!

**Comment by valeu** [comment]
Do not merge the overlapping regions, please! It is not good - you will loose in precision and also quality of fit/normalization. Just do something with these several regions that start at the same position. Just shift by one position or remove one of the regions, for example,
