### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by fengdong110** [BoevaLab/FREEC#5]
Hi，

I use the control_freec(v9.6) Analysis my Target sequencing data,
but I get the follows error: 

..............
..using GC-content to normalize copy number profiles
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
已放弃 (core dumped)

some people say is "Memory read cross-border".
How to solve this error?  
Thank you very much !!!

my config as follow:
[general]
  4 
  5 chrLenFile = /share/f/03.soft/FREEC/test/hg19.fa.fai
  6 window = 0
  7 ploidy = 2
  8 outputDir = /share/f/03.soft/FREEC/test/out/
  9 #sex=XY
 10 breakPointType=4
 11 chrFiles =  /share/f/03.soft/FREEC/test/chromosomes/
 12 maxThreads=6
 13 breakPointThreshold=0.8
 14 noisyData=TRUE
 15 printNA=FALSE
 16 readCountThreshold=50
 17 
 18 [sample]
 19 
 20 mateFile = /share/f/03.soft/FREEC/test/cancer.mpileup.txt
 21 inputFormat = pileup
 22 mateOrientation = FR
 23 
 24 [control]
 25 
 26 mateFile = /share/f/03.soft/FREEC/test/normal.mpileup.txt
 27 inputFormat = pileup
 28 mateOrientation = FR
 29 
 30 [BAF]
 31 
 32 #SNPfile = /bioinfo/users/vboeva/Desktop/annotations/hg19_snp131.SingleDiNucl.1based.txt
 33 #minimalCoveragePerPosition = 5
 34 
 35 [target]
 36 
 37 captureRegions = /share/f/03.soft/FREEC/test/sorted.bed

**Comment by valeu** [comment]
Dear Feng Dong,
In case of troubles like this you should send me a complete output into the command line. Otherwise, it is impossible to say what went wrong. Also, I would like to see the first lines of your pileup files.

**Comment by valeu** [comment]
Was your issue solved by using v9.9?

**Comment by valeu** [comment]
I believed that the fix in v10.2 should solve this issue.

**Comment by skenoy** [comment]
I use 10.4, it`s still the same error

**Comment by valeu** [comment]
I would be happy to debug. Can you share the input files and the config, please?

**Comment by michelled3** [comment]
Hello, I have the same problem and I am using v10.2. How could I share the files with you to debug for this error? Thank you!

**Comment by valeu** [comment]
Dear Michelle, can you use an FTP server, dropbox, or something similar? Unfortunately, we do not have have an FTP ourselves.
