### ISSUE TITLE
Error of makeGraph.R

### ISSUE THREAD

**Issue by Tina9** [BoevaLab/FREEC#55]
Hi there,

`Error in plot.window(...) : need finite 'xlim' values` was reported when I used the command line `cat makeGraph.R | R --slave --args 2 *ratio_noNA.txt`.

![image](https://user-images.githubusercontent.com/16876314/60574177-ada8cc80-9dab-11e9-9b1e-8912533626da.png)

I already delete all the 'Y' in the R script since Y chromosome is not included in my data. I am really wondering what happened.

Best,
Tina

**Comment by valeu** [comment]
Dear Tina,
did you look at the _ratio.txt file - does it contain any values different from "-1"?
You do not profide a _BAF.txt file, right?

**Comment by Tina9** [comment]
I deleted all these rows with ration equals to -1 according to the manual.

Yes, I didn't provide the BAF.txt file.

**Comment by valeu** [comment]
Can you share your _ratio.txt file, please?

**Comment by Tina9** [comment]
[tmp_ratio_noNA.txt](https://github.com/BoevaLab/FREEC/files/3449360/tmp_ratio_noNA.txt)
[tmp_023_ratio_noNA.txt](https://github.com/BoevaLab/FREEC/files/3449361/tmp_023_ratio_noNA.txt)
And my command line is `cat ~/softwares/FREEC-11.4/scripts/makeGraph.R| R --slave --args 2 tmp*.txt`.

The error message is as follows:
![image](https://user-images.githubusercontent.com/16876314/62176107-d1dbd700-b372-11e9-8e3c-75c507251ce1.png)

**Comment by valeu** [comment]
Thank you Tina. I think what is going on is that you want type "--args 2 tmp*.txt" you provide both ratio files to the R script. And the program thinks that the second file is a file with .BAF information and outputs an error. However, it looks like at least one .png file is created for the first tmp.xxx.txt file you provide. Is it the case?
Can you run separately  

`cat ~/softwares/FREEC-11.4/scripts/makeGraph.R| R --slave --args 2 tmp_023_ratio_noNA.txt`

and

`cat ~/softwares/FREEC-11.4/scripts/makeGraph.R| R --slave --args 2 tmp_ratio_noNA.txt`

Does it give you an error too?

**Comment by Tina9** [comment]
Yes, it is the key.

Thanks for your help again.
