### ISSUE TITLE
explanation of ratio in *_ratio.txt

### ISSUE THREAD

**Issue by Tina9** [BoevaLab/FREEC#56]
Hi,

When I read the manual of Control-Freec, I found that ratio = (Sample RC/ Control RC). Is it the meaning of Ration and MedianRatio in the result of *_ratio.txt?

Thanks

**Comment by valeu** [comment]
yes, if you use a control file and do not force GC-content-based normalization by using "ForceGCnormalization" or providing [BAF] options, or using FREEC without a control sample. In the latter cases, "ratio" is the result of normalization of read count versus GC-content. It is:

Ratio=ReadCount/ExpectedReadCountGivenGCcontentObserved

Ratio is equal to 1 in copy neutral regions.

**Comment by Tina9** [comment]
Thanks for your explanation.
