### ISSUE TITLE
cannot "make" free from version 9.7 source file 

### ISSUE THREAD

**Issue by hongenxu** [BoevaLab/FREEC#6]
Hi, 

I tried make freec from source file in three different computers, none works. 
below is the output message: 

make -f Makefile.freec init
make[1]: Entering directory `/home/users/xu/FREEC-9.7/src'
make[1]: Nothing to be done for `init'.
make[1]: Leaving directory `/home/users/xu/FREEC-9.7/src'
make -f Makefile.freec depend
make[1]: Entering directory `/home/users/xu/FREEC-9.7/src'
make[1]: Leaving directory `/home/users/xu/FREEC-9.7/src'
make -f Makefile.freec all
make[1]: Entering directory `/home/users/xu/FREEC-9.7/src'
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o main.o main.cpp
main.cpp: In function ‘int main(int, char**)’:
main.cpp:541:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int i = 0; i < strs.size(); i++)   {
                                       ^
main.cpp:577:60: warning: statement has no effect [-Wunused-value]
     if (seekSubclones==0  ||seekSubclones==1) {seekSubclones==100;}
                                                            ^
main.cpp:904:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i=0;i < ploidies.size(); i++ ) {
                                    ^
main.cpp:915:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i=0;i < ploidies.size(); i++ ) {
                                    ^
main.cpp:536:10: warning: variable ‘isPloidyKnown’ set but not used [-Wunused-but-set-variable]
     bool isPloidyKnown = false;
          ^
main.cpp: In function ‘void runWithDefinedPloidy(int, GenomeCopyNumber&, GenomeCopyNumber&, bool, int, bool, bool, bool, int, int, bool, float, float, float, float, int, int, int, std::vector<double>&, std::vector<double>&, bool, std::vector<double>&, ThreadPool*, ThreadPoolManager*, std::string, float, std::string, std::vector<int>&, bool)’:
main.cpp:1020:27: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
             if ((!forceGC && !(has_BAF) || (ifTargeted&&forceGC!=1) || (WESanalysis == true &&forceGC==0))) { //normalize sample density with control density
                           ^
main.cpp:1179:48: warning: ‘contamValue’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             contamination.push_back(contamValue);
                                                ^
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o ConfigFile.o ConfigFile.cpp
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o Chameleon.o Chameleon.cpp
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o GenomeDensity.o GenomeDensity.cpp
GenomeDensity.cpp: In constructor ‘GenomeDensity::GenomeDensity(const string&, const string&, const string&, const string&)’:
GenomeDensity.cpp:63:10: warning: unused variable ‘length’ [-Wunused-variable]
      int length = strs[1].length();
          ^
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o Help.o Help.cpp
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o myFunc.o myFunc.cpp
myFunc.cpp: In function ‘unsigned int split(char*, char, char**)’:
myFunc.cpp:54:18: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
   for (; c = *str++; ++jj) {
                  ^
myFunc.cpp: In function ‘long int getReadNumberFromPileup(const string&)’:
myFunc.cpp:370:56: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
                 if (toadd=strccnt(strs[4].c_str(), '^')) {
                                                        ^
myFunc.cpp:393:56: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
                 if (toadd=strccnt(strs[4].c_str(), '^')) {
                                                        ^
myFunc.cpp: In function ‘void strkeepOnly(char*, const char*)’:
myFunc.cpp:1639:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i< strlen(s);i++) {
                                ^
myFunc.cpp:1640:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int j = 0; j< strlen(c);j++){
                                    ^
myFunc.cpp: In function ‘void strkeepOnly(std::string&, const char*)’:
myFunc.cpp:1651:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i< s.length(); i++) {
                                 ^
myFunc.cpp:1652:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int j = 0; j< strlen(c);j++){
                                    ^
myFunc.cpp: In function ‘void deleteChar(std::string&, char, int)’:
myFunc.cpp:1672:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i< s.length(); i++) {
                                 ^
myFunc.cpp: In function ‘void deleteChar(std::string&, char)’:
myFunc.cpp:1686:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i< s.length(); i++) {
                                 ^
myFunc.cpp: In function ‘void filterWithQualities(std::string&, std::string&, int)’:
myFunc.cpp:1709:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i< pileupShort.length(); i++) {
                                           ^
myFunc.cpp: In function ‘void getBAFinfo(std::string, float, float&, float&, std::string&, float&, float, int, bool, bool, bool)’:
myFunc.cpp:1886:141: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
             if (copyNumbers[0]==1 && copyNumbers[1]==2 && copyNumber<1.5 && (medianBAFSym.compare("AA")==0 || medianBAFSym.compare("AB")==0 && uncertainty >0.1)) {
                                                                                                                                             ^
myFunc.cpp:1908:48: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for(int jj=0; jj<testedCN.size();jj++) {
                                                ^
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o KernelVector.o KernelVector.cpp
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o ChrDensity.o ChrDensity.cpp
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o ChrCopyNumber.o ChrCopyNumber.cpp
ChrCopyNumber.cpp: In constructor ‘ChrCopyNumber::ChrCopyNumber(int, int, const string&, int, std::string)’:
ChrCopyNumber.cpp:210:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if(tried != length_) {
                         ^
ChrCopyNumber.cpp: In member function ‘std::string ChrCopyNumber::getGeneNameAtBin(int)’:
ChrCopyNumber.cpp:359:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (genes_names.size()>=i)
                             ^
ChrCopyNumber.cpp: In member function ‘void ChrCopyNumber::setNotNprofileAt(int, float)’:
ChrCopyNumber.cpp:383:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (i<notNprofile_.size())
                             ^
ChrCopyNumber.cpp: In member function ‘void ChrCopyNumber::setAllNormal()’:
ChrCopyNumber.cpp:581:50: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (readCount_[i] != NA && i<notNprofile_.size() &&notNprofile_[i]>0) {
                                                  ^
ChrCopyNumber.cpp: In member function ‘void ChrCopyNumber::calculateCopyNumberMedian(int, int, bool, bool)’:
ChrCopyNumber.cpp:732:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (medianProfile_.size()!=length_) {
                                ^
ChrCopyNumber.cpp:792:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (data.size()>=minCNAlength && data.size()>0)
                          ^
ChrCopyNumber.cpp: In member function ‘float ChrCopyNumber::getEstimatedBAFuncertaintyAtI(int)’:
ChrCopyNumber.cpp:1552:47: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (i>0 &&i<estimatedBAFuncertainty_.size())
                                               ^
ChrCopyNumber.cpp: In member function ‘void ChrCopyNumber::setRCountToZeroForNNNN()’:
ChrCopyNumber.cpp:1704:42: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i< notNprofile_.size(); i++) {
                                          ^
ChrCopyNumber.cpp:1709:58: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = notNprofile_.size(); i< readCount_.size(); i++) {
                                                          ^
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o GenomeCopyNumber.o GenomeCopyNumber.cpp
GenomeCopyNumber.cpp: In member function ‘double GenomeCopyNumber::calculateMedianAround(GenomeCopyNumber&, float, float)’:
GenomeCopyNumber.cpp:1012:53: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (controlcounts.size()!=it->getLength()) {
                                                     ^
GenomeCopyNumber.cpp: In member function ‘void GenomeCopyNumber::calculateRatio(GenomeCopyNumber&, int, bool, bool)’:
GenomeCopyNumber.cpp:1134:57: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 if (controlcounts.size()!=it->getLength()) {
                                                         ^
GenomeCopyNumber.cpp:1345:57: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 if (controlcounts.size()!=it->getLength()) {
                                                         ^
GenomeCopyNumber.cpp: In member function ‘float GenomeCopyNumber::evaluateContaminationwithLR()’:
GenomeCopyNumber.cpp:3229:8: warning: unused variable ‘contam’ [-Wunused-variable]
  float contam = 0;
        ^
GenomeCopyNumber.cpp: In member function ‘int GenomeCopyNumber::processRead(const string&, const string&, std::string)’:
GenomeCopyNumber.cpp:3623:55: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
        if (valueToReturn=strccnt(strs[4].c_str(), '^')) {
                                                       ^
GenomeCopyNumber.cpp: In member function ‘int GenomeCopyNumber::processRead(InputFormat, MateOrientation, const char*, int&, std::string, std::string)’:
GenomeCopyNumber.cpp:3691:29: warning: unused variable ‘maxpos’ [-Wunused-variable]
                         int maxpos=0;
                             ^
GenomeCopyNumber.cpp:4072:20: warning: unused variable ‘orient2_1’ [-Wunused-variable]
    MateOrientation orient2_1 = getMateOrientation(orient2+orient1);
                    ^
GenomeCopyNumber.cpp:4192:43: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
    if (valueToReturn=strccnt(strs[4], '^')) {
                                           ^
GenomeCopyNumber.cpp: In member function ‘int GenomeCopyNumber::focusOnCapture(const string&)’:
GenomeCopyNumber.cpp:4359:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (RegLength<minRegion)
                           ^
GenomeCopyNumber.cpp: In member function ‘double GenomeCopyNumber::Percentage_GenomeExplained(int&)’:
GenomeCopyNumber.cpp:4453:8: warning: unused variable ‘startFragment’ [-Wunused-variable]
    int startFragment = 0;
        ^
GenomeCopyNumber.cpp:4454:8: warning: unused variable ‘endFragment’ [-Wunused-variable]
    int endFragment=0;
        ^
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o chisquaredistr.o chisquaredistr.cpp
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o ap.o ap.cpp
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o igammaf.o igammaf.cpp
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o gammafunc.o gammafunc.cpp
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o normaldistr.o normaldistr.cpp
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o ablasf.o ablasf.cpp
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o ablas.o ablas.cpp
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o ortfac.o ortfac.cpp
ortfac.cpp: In function ‘void rmatrixbd(ap::real_2d_array&, int, int, ap::real_1d_array&, ap::real_1d_array&)’:
ortfac.cpp:1421:9: warning: variable ‘minmn’ set but not used [-Wunused-but-set-variable]
     int minmn;
         ^
ortfac.cpp: In function ‘void rmatrixlqbasecase(ap::real_2d_array&, int, int, ap::real_1d_array&, ap::real_1d_array&, ap::real_1d_array&)’:
ortfac.cpp:2927:9: warning: variable ‘minmn’ set but not used [-Wunused-but-set-variable]
     int minmn;
         ^
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o sblas.o sblas.cpp
sblas.cpp: In function ‘void symmetricmatrixvectormultiply(const real_2d_array&, bool, int, int, const real_1d_array&, double, ap::real_1d_array&)’:
sblas.cpp:40:9: warning: variable ‘ba2’ set but not used [-Wunused-but-set-variable]
     int ba2;
         ^
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o rotations.o rotations.cpp
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o reflections.o reflections.cpp
reflections.cpp: In function ‘void applyreflectionfromtheleft(ap::real_2d_array&, double, const real_1d_array&, int, int, int, int, ap::real_1d_array&)’:
reflections.cpp:199:9: warning: variable ‘vm’ set but not used [-Wunused-but-set-variable]
     int vm;
         ^
reflections.cpp: In function ‘void applyreflectionfromtheright(ap::real_2d_array&, double, const real_1d_array&, int, int, int, int, ap::real_1d_array&)’:
reflections.cpp:270:9: warning: variable ‘vm’ set but not used [-Wunused-but-set-variable]
     int vm;
         ^
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o linreg.o linreg.cpp
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o hblas.o hblas.cpp
hblas.cpp: In function ‘void hermitianmatrixvectormultiply(const complex_2d_array&, bool, int, int, const complex_1d_array&, ap::complex, ap::complex_1d_array&)’:
hblas.cpp:40:9: warning: variable ‘ba2’ set but not used [-Wunused-but-set-variable]
     int ba2;
         ^
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o descriptivestatistics.o descriptivestatistics.cpp
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o creflections.o creflections.cpp
creflections.cpp: In function ‘void complexapplyreflectionfromtheleft(ap::complex_2d_array&, ap::complex, const complex_1d_array&, int, int, int, int, ap::complex_1d_array&)’:
creflections.cpp:206:9: warning: variable ‘vm’ set but not used [-Wunused-but-set-variable]
     int vm;
         ^
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o blas.o blas.cpp
blas.cpp: In function ‘int vectoridxabsmax(const real_1d_array&, int, int)’:
blas.cpp:71:12: warning: variable ‘a’ set but not used [-Wunused-but-set-variable]
     double a;
            ^
blas.cpp: In function ‘int columnidxabsmax(const real_2d_array&, int, int, int)’:
blas.cpp:90:12: warning: variable ‘a’ set but not used [-Wunused-but-set-variable]
     double a;
            ^
blas.cpp: In function ‘int rowidxabsmax(const real_2d_array&, int, int, int)’:
blas.cpp:109:12: warning: variable ‘a’ set but not used [-Wunused-but-set-variable]
     double a;
            ^
blas.cpp: In function ‘void matrixmatrixmultiply(const real_2d_array&, int, int, int, int, bool, const real_2d_array&, int, int, int, int, bool, double, ap::real_2d_array&, int, int, int, int, double, ap::real_1d_array&)’:
blas.cpp:388:9: warning: variable ‘ccols’ set but not used [-Wunused-but-set-variable]
     int ccols;
         ^
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o bdsvd.o bdsvd.cpp
bdsvd.cpp: In function ‘bool bidiagonalsvddecompositioninternal(ap::real_1d_array&, ap::real_1d_array, int, bool, bool, ap::real_2d_array&, int, int, ap::real_2d_array&, int, int, ap::real_2d_array&, int, int)’:
bdsvd.cpp:234:12: warning: variable ‘sminlo’ set but not used [-Wunused-but-set-variable]
     double sminlo;
            ^
bdsvd.cpp:252:10: warning: variable ‘rightside’ set but not used [-Wunused-but-set-variable]
     bool rightside;
          ^
bdsvd.cpp:1030:5: warning: ‘tsign’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     if( ap::fp_greater_eq(b,0) )
     ^
bdsvd.cpp:1146:12: note: ‘tsign’ was declared here
     double tsign;
            ^
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o svd.o svd.cpp
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o ialglib.o ialglib.cpp
ialglib.cpp: In function ‘bool ialglib::_i_cmatrixgemmf(int, int, int, ap::complex, const complex_2d_array&, int, int, int, const complex_2d_array&, int, int, int, ap::complex, ap::complex_2d_array&, int, int)’:
ialglib.cpp:837:48: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
    vcopy_complex(k, arow, 1, abuf, 1, "No conj");
                                                ^
ialglib.cpp:842:62: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
             vcopy_complex(k, arow, stride, abuf, 1, "No conj");
                                                              ^
ialglib.cpp:847:59: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
             vcopy_complex(k, arow, stride, abuf, 1, "Conj");
                                                           ^
ialglib.cpp: In function ‘bool ialglib::_i_cmatrixrighttrsmf(int, int, const complex_2d_array&, int, int, bool, bool, int, ap::complex_2d_array&, int, int)’:
ialglib.cpp:917:76: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
             vcopy_complex(i, abuf+2*i, alglib_c_block, tmpbuf, 1, "No conj");
                                                                            ^
ialglib.cpp:930:94: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
             vcopy_complex(n-1-i, pdiag+2*alglib_c_block, alglib_c_block, tmpbuf, 1, "No conj");
                                                                                              ^
ialglib.cpp: In function ‘bool ialglib::_i_cmatrixlefttrsmf(int, int, const complex_2d_array&, int, int, bool, bool, int, ap::complex_2d_array&, int, int)’:
ialglib.cpp:1069:66: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
             vcopy_complex(m-1-i, pdiag+2, 1, tmpbuf, 1, "No conj");
                                                                  ^
ialglib.cpp:1081:59: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
             vcopy_complex(i, arow, 1, tmpbuf, 1, "No conj");
                                                           ^
ialglib.cpp: In function ‘bool ialglib::_i_cmatrixsyrkf(int, int, double, const complex_2d_array&, int, int, int, double, ap::complex_2d_array&, int, int, bool)’:
ialglib.cpp:1229:56: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
             vcopy_complex(k, arow, 1, tmpbuf, 1, "Conj");
                                                        ^
ialglib.cpp:1237:56: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
             vcopy_complex(k, arow, 1, tmpbuf, 1, "Conj");
                                                        ^
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o EntryCNV.o EntryCNV.cpp
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o SNPinGenome.o SNPinGenome.cpp
SNPinGenome.cpp: In member function ‘int SNPinGenome::processSNPLine(bool, char*, std::string&, int&, int&)’:
SNPinGenome.cpp:58:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (SNP_atChr_->size()>index) {
                                    ^
SNPinGenome.cpp: In member function ‘long int SNPinGenome::processPileUPLine(int&, char*, std::string&, int&, int, int&, int, GenomeCopyNumber*)’:
SNPinGenome.cpp:273:62: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
                     if (valueToReturn = strccnt(strs[4], '^')) {
                                                              ^
SNPinGenome.cpp:287:62: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
                     if (valueToReturn = strccnt(strs[4], '^')) {
                                                              ^
SNPinGenome.cpp:316:19: warning: unused variable ‘localBAF’ [-Wunused-variable]
             float localBAF=addInfoFromAPileUp(atoi(strs[3]),minimalTotalLetterCountPerPosition,(*SNP_atChr_)[index].getNucleotideAt(positionCount),
                   ^
SNPinGenome.cpp:338:27: warning: unused variable ‘localBAF’ [-Wunused-variable]
                     float localBAF=addInfoFromAPileUp(atoi(strs[3]),minimalTotalLetterCountPerPosition,(*SNP_atChr_)[index].getNucleotideAt(positionCount),
                           ^
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o SNPatChr.o SNPatChr.cpp
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o SNPposition.o SNPposition.cpp
SNPposition.cpp: In constructor ‘SNPposition::SNPposition(int, char*)’:
SNPposition.cpp:31:18: warning: unused variable ‘strs_cnt’ [-Wunused-variable]
         unsigned strs_cnt = split(alt, ',', strs);
                  ^
SNPposition.cpp: In constructor ‘SNPposition::SNPposition(int, char*, const char*, const char*)’:
SNPposition.cpp:46:14: warning: unused variable ‘c_ref’ [-Wunused-variable]
         char c_ref = ref[0];
              ^
SNPposition.cpp:47:14: warning: unused variable ‘reverse’ [-Wunused-variable]
         bool reverse = strcmp(strand, "-") == 0;
              ^
SNPposition.cpp:52:18: warning: unused variable ‘strs_cnt’ [-Wunused-variable]
         unsigned strs_cnt = split(letters, '/', strs);
                  ^
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o binomialdistr.o binomialdistr.cpp
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o ibetaf.o ibetaf.cpp
ibetaf.cpp: In function ‘double invincompletebeta(double, double, double)’:
ibetaf.cpp:258:9: warning: ‘dir’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     int dir;
         ^
ibetaf.cpp:433:25: warning: ‘rflg’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                         if( rflg==1 )
                         ^
ibetaf.cpp:397:21: warning: ‘dithresh’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                     if( ap::fp_less(fabs(yp),dithresh) )
                     ^
ibetaf.cpp:579:62: warning: ‘lgm’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                 d = (aaa-1.0)*log(x)+(bbb-1.0)*log(1.0-x)+lgm;
                                                              ^
ibetaf.cpp:546:54: warning: ‘x’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                     yyy = incompletebeta(aaa, bbb, x);
                                                      ^
ibetaf.cpp:548:17: warning: ‘yyy’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                 if( ap::fp_less(yyy,yl) )
                 ^
ibetaf.cpp:396:30: warning: ‘y0’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                     yp = (yyy-y0)/y0;
                              ^
ibetaf.cpp:579:42: warning: ‘bbb’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                 d = (aaa-1.0)*log(x)+(bbb-1.0)*log(1.0-x)+lgm;
                                          ^
ibetaf.cpp:579:25: warning: ‘aaa’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                 d = (aaa-1.0)*log(x)+(bbb-1.0)*log(1.0-x)+lgm;
                         ^
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o ThreadPool.o ThreadPool.cpp
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o BAFpileup.o BAFpileup.cpp
BAFpileup.cpp: In member function ‘float BAFpileup::calculateFlankLength(const string&, const string&, const string&, std::string)’:
BAFpileup.cpp:54:20: warning: unused variable ‘t0’ [-Wunused-variable]
             time_t t0 = time(NULL);
                    ^
BAFpileup.cpp:57:25: warning: unused variable ‘matesOrientation’ [-Wunused-variable]
         MateOrientation matesOrientation = getMateOrientation(matesOrientation_str);
                         ^
BAFpileup.cpp: In member function ‘void BAFpileup::createBedFileWithChromosomeLengths(std::string, std::string)’:
BAFpileup.cpp:212:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < chr_names.size(); i++)
                                        ^
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o RSSerror.o RSSerror.cpp
In file included from RSSerror.h:13:0,
                 from RSSerror.cpp:1:
GenomeCopyNumber.h: In function ‘long double calculateRSS(GenomeCopyNumber&, int)’:
GenomeCopyNumber.h:134:29: error: ‘std::map<std::basic_string<char>, int> GenomeCopyNumber::chromosomesInd_’ is private
  std::map<std::string, int> chromosomesInd_; //should stay private
                             ^
RSSerror.cpp:15:28: error: within this context
  for ( it=samplecopynumber.chromosomesInd_.begin() ; it != samplecopynumber.chromosomesInd_.end(); it++ ) {
                            ^
In file included from RSSerror.h:13:0,
                 from RSSerror.cpp:1:
GenomeCopyNumber.h:134:29: error: ‘std::map<std::basic_string<char>, int> GenomeCopyNumber::chromosomesInd_’ is private
  std::map<std::string, int> chromosomesInd_; //should stay private
                             ^
RSSerror.cpp:15:77: error: within this context
  for ( it=samplecopynumber.chromosomesInd_.begin() ; it != samplecopynumber.chromosomesInd_.end(); it++ ) {
                                                                             ^
In file included from RSSerror.h:13:0,
                 from RSSerror.cpp:1:
GenomeCopyNumber.h:133:32: error: ‘std::vector<ChrCopyNumber> GenomeCopyNumber::chrCopyNumber_’ is private
     std::vector<ChrCopyNumber> chrCopyNumber_; //should stay private !!! why is it public now, Carino????
                                ^
RSSerror.cpp:24:33: error: within this context
   int length = samplecopynumber.chrCopyNumber_[index].getLength();
                                 ^
In file included from RSSerror.h:13:0,
                 from RSSerror.cpp:1:
GenomeCopyNumber.h:133:32: error: ‘std::vector<ChrCopyNumber> GenomeCopyNumber::chrCopyNumber_’ is private
     std::vector<ChrCopyNumber> chrCopyNumber_; //should stay private !!! why is it public now, Carino????
                                ^
RSSerror.cpp:29:45: error: within this context
                 observed = samplecopynumber.chrCopyNumber_[index].getRatioAtBin(i);
                                             ^
In file included from RSSerror.h:13:0,
                 from RSSerror.cpp:1:
GenomeCopyNumber.h:133:32: error: ‘std::vector<ChrCopyNumber> GenomeCopyNumber::chrCopyNumber_’ is private
     std::vector<ChrCopyNumber> chrCopyNumber_; //should stay private !!! why is it public now, Carino????
                                ^
RSSerror.cpp:31:38: error: within this context
                 if (samplecopynumber.chrCopyNumber_[index].isMedianCalculated()) {
                                      ^
In file included from RSSerror.h:13:0,
                 from RSSerror.cpp:1:
GenomeCopyNumber.h:133:32: error: ‘std::vector<ChrCopyNumber> GenomeCopyNumber::chrCopyNumber_’ is private
     std::vector<ChrCopyNumber> chrCopyNumber_; //should stay private !!! why is it public now, Carino????
                                ^
RSSerror.cpp:32:49: error: within this context
                     expected = samplecopynumber.chrCopyNumber_[index].getMedianProfileAtI(i);
                                                 ^
In file included from RSSerror.h:13:0,
                 from RSSerror.cpp:1:
GenomeCopyNumber.h:133:32: error: ‘std::vector<ChrCopyNumber> GenomeCopyNumber::chrCopyNumber_’ is private
     std::vector<ChrCopyNumber> chrCopyNumber_; //should stay private !!! why is it public now, Carino????
                                ^
RSSerror.cpp:33:42: error: within this context
                     if (samplecopynumber.chrCopyNumber_[index].isSmoothed())
                                          ^
In file included from RSSerror.h:13:0,
                 from RSSerror.cpp:1:
GenomeCopyNumber.h:133:32: error: ‘std::vector<ChrCopyNumber> GenomeCopyNumber::chrCopyNumber_’ is private
     std::vector<ChrCopyNumber> chrCopyNumber_; //should stay private !!! why is it public now, Carino????
                                ^
RSSerror.cpp:34:53: error: within this context
                         expected = samplecopynumber.chrCopyNumber_[index].getSmoothedProfileAtI(i);
                                                     ^
make[1]: *** [RSSerror.o] Error 1
make[1]: Leaving directory `/home/users/xu/FREEC-9.7/src'
make: *** [all] Error 2

**Comment by valeu** [comment]
Oh, sorry! you should remove RSSerror.cpp and RSSerror.h functions completely. I forgot to do it in v9.7.
Then try:
make clean
make

**Comment by valeu** [comment]
And I forgot to update the Makefile: please remove RSSerror.o from it.

**Comment by hongenxu** [comment]
thanks, it works.
