### ISSUE TITLE
seg files from Freec outputs

### ISSUE THREAD

**Issue by kgaonkar6** [BoevaLab/FREEC#60]
Hello,

I am trying to convert freec outputs to segmentation file format to run it through GISTIC/visualization. Do you have any recommended methods to convert the *ratio.txt files to seg files (using DNAcopy R package or something similar)? 

Researching about what other people have done I've wrote this script https://gist.github.com/kgaonkar6/2e84a21adea23003b7d1d7d33c1619a4 let me know what you would suggest.

Thanks,
Krutika

**Comment by valeu** [comment]
Dear Krutika,
Thank you for your question. I don't have a script to do the format conversion. But I would be happy to add it to the package if you write it.
Best 
Valentina

**Comment by februaryfang** [comment]
hello,
Do you have a script to convert the *ratio.txt file to seg file now? Can I use DNAcopy R package?
I know the input of DNAcopy is logratio. Is it different from ratio from *ratio.txt file?
Please let me know.

Thanks.
Fang

**Comment by februaryfang** [comment]
hi，
I got *_ratio.txt from FREEC soft. Next step I want to use GISTIC2 software for analysis, which requires input of segmentation file. The header includes 'ID, chrom, loc.start, loc.end, num.mark, seg.mean'. So how can I get this information from the *_ratio.txt file ? Can I use DNAcopy R package? The input of DNAcopy is logratio. Is it different from ratio from *ratio.txt file?

Best
Fang

**Comment by februaryfang** [comment]
hello,
I got *_ratio.txt from FREEC soft. Next step I want to use GISTIC2 software for analysis, which requires input of segmentation file. The header includes 'ID, chrom, loc.start, loc.end, num.mark, seg.mean'. So how can I get this information from the *_ratio.txt file ? Can I use DNAcopy R package? The input of DNAcopy is logratio. Is it different from ratio from *ratio.txt file?

Best
Fang

**Comment by valeu** [comment]
Dear Fang, I guess the script I have created to answer to this thread will do what you need: 

[(https://github.com/BoevaLab/FREEC/issues/118)](https://github.com/BoevaLab/FREEC/issues/118)

It will however output log2(Segment Median) and not the mean. This can result in -inf values

**Comment by februaryfang** [comment]
Dear @valeu,  You solved my problem. Thank you very much for your reply!
