### ISSUE TITLE
Using long reads in Control-FREEC

### ISSUE THREAD

**Issue by gbdias** [BoevaLab/FREEC#64]
Hi,

I understand the software was designed for short-read data, but do you anticipate any specific problems if one were to use long read BAM files for CNV detection with FREEC?

Thanks,
Guilherme Dias

**Comment by valeu** [comment]
Dear Guiherme,
technically it will work. Then you can visualize the resulting copy number profiles using the attached .R script to see whether you can trust the results.

**Comment by gbdias** [comment]
Thanks for the quick reply Valentina.

- In some initial testing we noticed a much larger dispersion in the DNAseq ratios for PacBio data versus Illumina for the same sample, which resulted in more CNVs being called when using PacBio (roughly 10x more than Illumina).

<img width="187" alt="Screen Shot 2019-10-04 at 2 18 05 PM" src="https://user-images.githubusercontent.com/7614153/66230365-068d4700-e6b2-11e9-87fa-eb6f72b7377e.png">

- I am currently doing some QC and also removing duplicate subreads that come from the same polymerase read to see if this dispersion diminishes and results converge with Illumina.
- Another difference is the use of mappability information. Since PacBio reads are long, it shouldn't be necessary to use mappability info when running FREEC. Do you think that's reasonable?

Best,
Guilherme

**Comment by valeu** [comment]
You are right that you should not use the mappability tracks with PacBio. Do you use any control data or not?

**Comment by gbdias** [comment]
Hi @valeu, I did not use any control data.
I will close this issue since there might be quality issues with our pacbio data. I will do more testing with different datasets.
