### ISSUE TITLE
Is there a minimum number for the number of amplicons?

### ISSUE THREAD

**Issue by yuyuliu** [BoevaLab/FREEC#69]
I am applying control-FREEC on custom target gene sequencing data with predesigned custom panels.
I have one dataset with 15991 targeted amplicons distributed on almost all chromosomes. FREEC worked very well for this dataset.
However, I have a second dataset with only 364 amplicons on only 4 chromosomes.
I tried to change different parameters in the config file but nothing worked.
This is what I get every time:

> PROFILING [tid=0x7000006c4000]: 1tumor.pileup read in 1 seconds [assignValues]
will skip chr14
will skip chr14_GL000225v1_random
will skip chr14_KI270725v1_random
will skip chr15
will skip chr15_KI270905v1_alt
will skip chr16
will skip chr16_GL383557v1_alt
will skip chr17
will skip chr17_KI270862v1_alt
will skip chr17_KI270908v1_alt
will skip chr18
will skip chr19
will skip chr20
will skip chr21
will skip chr22
will skip chrX
will skip chrX_KI270880v1_alt
will skip chrX_KI270913v1_alt
will skip chrY
0 reads used to compute copy number profile
133412 lines read
PROFILING [tid=0x700000747000]: 1normal.pileup read in 1 seconds [assignValues]
printing counts into ./try5/1tumor.pileup_sample.cpn
printing counts into ./try5/1normal.pileup_control.cpn
..FREEC will take into account only regions from Targets_wochr_sorted.bed
..will remove all windows with read count in the control less than 10
..will process the control file as well: removing all windows with read count in the control less than 10
..Set ploidy for the control genome equal to 2
..Running FREEC with ploidy set to 2
..polynomial degree set to 1
Initial guess for polynomial:
Error: no windows with reads
Unable to proceed..

**Comment by valeu** [comment]
For this design: 364 amplicons on only 4 chromosomes - I suggest to use OncoCNV instead.

**Comment by yuyuliu** [comment]
> For this design: 364 amplicons on only 4 chromosomes - I suggest to use OncoCNV instead.

Thank you very much for the answer!
