### ISSUE TITLE
compile error in 9.7

### ISSUE THREAD

**Issue by RichardCorbett** [BoevaLab/FREEC#7]
Hi there,

i compiled 9.6 without any errors, but when I "make" 9.7 I get:
`...
BAFpileup.cpp: In member function ‘void BAFpileup::createBedFileWithChromosomeLengths(std::string, std::string)’:
BAFpileup.cpp:212: warning: comparison between signed and unsigned integer expressions
g++ -O3 -g -DPROFILE_TRACE -Wall -m64   -c -o RSSerror.o RSSerror.cpp
GenomeCopyNumber.h: In function ‘long double calculateRSS(GenomeCopyNumber&, int)’:
GenomeCopyNumber.h:134: error: ‘std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> > > GenomeCopyNumber::chromosomesInd_’ is private
RSSerror.cpp:15: error: within this context
GenomeCopyNumber.h:134: error: ‘std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, int> > > GenomeCopyNumber::chromosomesInd_’ is private
RSSerror.cpp:15: error: within this context
GenomeCopyNumber.h:133: error: ‘std::vector<ChrCopyNumber, std::allocator<ChrCopyNumber> > GenomeCopyNumber::chrCopyNumber_’ is private
RSSerror.cpp:24: error: within this context
GenomeCopyNumber.h:133: error: ‘std::vector<ChrCopyNumber, std::allocator<ChrCopyNumber> > GenomeCopyNumber::chrCopyNumber_’ is private
RSSerror.cpp:29: error: within this context
GenomeCopyNumber.h:133: error: ‘std::vector<ChrCopyNumber, std::allocator<ChrCopyNumber> > GenomeCopyNumber::chrCopyNumber_’ is private
RSSerror.cpp:31: error: within this context
GenomeCopyNumber.h:133: error: ‘std::vector<ChrCopyNumber, std::allocator<ChrCopyNumber> > GenomeCopyNumber::chrCopyNumber_’ is private
RSSerror.cpp:32: error: within this context
GenomeCopyNumber.h:133: error: ‘std::vector<ChrCopyNumber, std::allocator<ChrCopyNumber> > GenomeCopyNumber::chrCopyNumber_’ is private
RSSerror.cpp:33: error: within this context
GenomeCopyNumber.h:133: error: ‘std::vector<ChrCopyNumber, std::allocator<ChrCopyNumber> > GenomeCopyNumber::chrCopyNumber_’ is private
RSSerror.cpp:34: error: within this context
make[1]: *** [RSSerror.o] Error 1
make[1]: Leaving directory `/home/rcorbett/bin/FREEC-9.7/src'
make: *** [all] Error 2
`

No big deal as I'm just testing this out and 9.6 should work for me, just flagged for you in case it helps.

**Comment by valeu** [comment]
Sorry, I was going to correct it today:

remove RSSerror.* files
and remove RSSerror.o from Makefile

Then it will compile.

**Comment by valeu** [comment]
solved in v9.8
