### ISSUE TITLE
bad alloc when running with GC correction

### ISSUE THREAD

**Issue by TracyBallinger** [BoevaLab/FREEC#8]
I'm running FREECv9.7b on an exome sequencing paired sample and getting a failure after the chromosome.lengths file is read. 
The end of the log file is below. 
Number of exons analysed in chromosome Y : 1321
..Starting reading /exports/igmm/eddie/TCGA_exome/WOLF/pileups/SOL1648_1.recal.pileup.gz
..finished reading /exports/igmm/eddie/TCGA_exome/WOLF/pileups/SOL1648_1.recal.pileup.gz
PROFILING [tid=47795198732096]: /exports/igmm/eddie/TCGA_exome/WOLF/pileups/SOL1648_1.recal.pileup.gz read in 453 seconds [fillMyHash]
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
49634942 lines read..
8281392 reads used to compute copy number profile
printing counts into ./freecout.GC1/tumour_normal/SOL1648_1.recal.pileup.gz_sample.cpn
..File /exports/igmm/eddie/TCGA_exome/WOLF/Homo_sapiens_assembly19.1.lengths was read

I'm attaching the config file, the output cpn file, the freec output (freec.log) and the file of chromosome lengths in this zip. 
[for_val2.zip](https://github.com/BoevaLab/FREEC/files/591782/for_val2.zip)

**Comment by valeu** [comment]
Solved in v10.2
