### ISSUE TITLE
Failed to open file "1" : No such file or directory

### ISSUE THREAD

**Issue by AlsoATraveler** [BoevaLab/FREEC#93]
Hi, what is the reason for the output such an error? how to solve it?

[opened FIFO for writing] /tmp/sambamba-pid6826-rhrg/3
[E::hts_open_format] Failed to open file "1" : No such file or directory
[mpileup] failed to open 1: No such file or directory
[opened FIFO for writing] /tmp/sambamba-pid6826-rhrg/2
[E::hts_open_format] Failed to open file "1" : No such file or directory
[mpileup] failed to open 1: No such file or directory
[opened FIFO for writing] /tmp/sambamba-pid6826-rhrg/5
[E::hts_open_format] Failed to open file "1" : No such file or directory
[mpileup] failed to open 1: No such file or directory
[opened FIFO for writing] /tmp/sambamba-pid6826-rhrg/1
[E::hts_open_format] Failed to open file "1" : No such file or directory
[mpileup] failed to open 1: No such file or directory
sambamba-pileup: Broken pipe
[E::hts_open_format] Failed to open file "/tmp/sambamba-pid6826-rhrg/8" : No such file or directory
[mpileup] failed to open /tmp/sambamba-pid6826-rhrg/8: No such file or directory
[E::hts_open_format] Failed to open file "/tmp/sambamba-pid6826-rhrg/12" : No such file or directory
[mpileup] failed to open /tmp/sambamba-pid6826-rhrg/12: No such file or directory
[E::hts_open_format] Failed to open file "/tmp/sambamba-pid6826-rhrg/7" : No such file or directory
[mpileup] failed to open /tmp/sambamba-pid6826-rhrg/7: No such file or directory
[E::hts_open_format] Failed to open file "/tmp/sambamba-pid6826-rhrg/4" : No such file or directory
[mpileup] failed to open /tmp/sambamba-pid6826-rhrg/4: No such file or directory
[E::hts_open_format] Failed to open file "/tmp/sambamba-pid6826-rhrg/6" : No such file or directory
[mpileup] failed to open /tmp/sambamba-pid6826-rhrg/6: No such file or directory
[E::hts_open_format] Failed to open file "/tmp/sambamba-pid6826-rhrg/10" : No such file or directory
[mpileup] failed to open /tmp/sambamba-pid6826-rhrg/10: No such file or directory
[E::hts_open_format] Failed to open file "/tmp/sambamba-pid6826-rhrg/9" : No such file or directory
[mpileup] failed to open /tmp/sambamba-pid6826-rhrg/9: No such file or directory
[E::hts_open_format] Failed to open file "/tmp/sambamba-pid6826-rhrg/13" : No such file or directory
[mpileup] failed to open /tmp/sambamba-pid6826-rhrg/13: No such file or directory
[E::hts_open_format] Failed to open file "/tmp/sambamba-pid6826-rhrg/11" : No such file or directory
[mpileup] failed to open /tmp/sambamba-pid6826-rhrg/11: No such file or directory
[E::hts_open_format] Failed to open file "/tmp/sambamba-pid6826-rhrg/14" : No such file or directory
[mpileup] failed to open /tmp/sambamba-pid6826-rhrg/14: No such file or directory
[E::hts_open_format] Failed to open file "/tmp/sambamba-pid6826-rhrg/15" : No such file or directory
[mpileup] failed to open /tmp/sambamba-pid6826-rhrg/15: No such file or directory
[E::hts_open_format] Failed to open file "/tmp/sambamba-pid6826-rhrg/16" : No such file or directory

**Comment by stroke1989** [comment]
I have encounterd the same promble to you. Have you solved this problem?

**Comment by yinbinqiu** [comment]
Error reporting Note: The chrLenFile and ploidy parameters need to be configured. If no control dataset is available, you must also specify chrFiles or GCcontentProfile.
If you provide the path to the chromosome file, Control-FREEC will look for the following fasta files in your directory (in this order): 1, 1.fa, 1.fasta, chr1.fa, chr1.fasta; 2, 2.fa, etc. Please make sure that there are no other files in this directory, but sequences with the listed names.

**Comment by valeu** [comment]
You can check whether you provide the full path to the directory with the chromosome fasta files. You can check the format of the chromosome length file. The names of the chromosomes there should be identical (+- chr +- file type) to the names of files with fasta.
