### ISSUE TITLE
Failed to run segmentation and segmentatuon fault (core dumped)

### ISSUE THREAD

**Issue by ahgillmo** [BoevaLab/FREEC#94]
Hello, I have been using control-freec for my research and have not had any issues so far. However, I am now running it on some new samples and have come into a segmentation and core dump issue. The code has been completed without errors on a sister sample that was sequenced, processed and aligned at the same time as this sample.

In my output error log, I get: Failed to run segmentation (on all chromosomes) followed by a core dump. ex.

..failed to run segmentation on chr1
..failed to run segmentation on chr2

followed by Segmentation fault (core dumped)

[controlfreec_running_11206557.err.txt](https://github.com/BoevaLab/FREEC/files/7331698/controlfreec_running_11206557.err.txt)

My config file is attached below:
[SM4228_PDX.SMmerge.lanemerged.sorted.markduplicates.bam.400000.controlfreec.config.txt](https://github.com/BoevaLab/FREEC/files/7331675/SM4228_PDX.SMmerge.lanemerged.sorted.markduplicates.bam.400000.controlfreec.config.txt)

Thank you for your time, 
aaron

**Comment by valeu** [comment]
Dear Aaron, 
I suggest that you run it with the following modifications in the Config. If you still get an error, please share the complete output into the command line.
Best
Valentina

```
[general]
chrLenFile=/master_scripts_slurm/controlFreeC_scripts/controlfreec_refData/controlfreec_hg38genome.fa.fai
ploidy=2
gemMappabilityFile=/master_scripts_slurm/controlFreeC_scripts/controlfreec_refData/out100m2_hg38.gem
#forceGCcontentNormalization=0
minCNAlength=1
#minimalSubclonePresence=20
sex=XY
contaminationAdjustment=TRUE
#window=400000
#step=400000
maxThreads=8
#degree=3,4
#intercept=0
#noisyData=FALSE
#uniqueMatch=TRUE
[sample]
mateFile=SM4228_PDX.SMmerge.lanemerged.sorted.markduplicates.bam
inputFormat=BAM
mateOrientation=FR
[control]
mateFile=SM3991_BLOOD_PTBN6150.SMmerge.lanemerged.sorted.markduplicates.bam
inputFormat=BAM
mateOrientation=FR
[BAF]
SNPfile=/master_scripts_slurm/controlFreeC_scripts/controlfreec_refData/baf_files/hg38_common_all_controlfreec_20180418.SNP.txt
fastaFile=/references/grch38_2-1-0/refdata-GRCh38-2.1.0/fasta/genome.fa
makePileup=/master_scripts_slurm/controlFreeC_scripts/controlfreec_refData/baf_files/hg38_common_all_controlfreec_20180418.SNP.txt.bed
shiftInQuality=33
minimalCoveragePerPosition=5
```
